language: java

jdk:
    - oraclejdk7

services:
    - mysql

before_install: 
    - mysql -uroot -e "grant all on jadwal.* to jadwal@localhost identified by 'jadwal'"
    - mysql -uroot -e "drop database if exists jadwal"
    - mysql -uroot -e "create database jadwal"

after_success:
    - mvn jacoco:report coveralls:report


